apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-manager
  labels:
    app: {{ .Values.manager.name }}
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - port: {{ .Values.manager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
     app: {{ .Values.manager.name }}
