---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
  namespace: potee
data:
  SRV_KEY: secret
  K3S_SRV: k3s-api
  OVPN_HOST: ovpn-admin-svc:8080
  OVPN_USER: alpha
  OVPN_PASSWORD: this-unusual-password
  DB_USER: gorm
  DB_PASSWORD: gorm
  DB_HOST: database
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: potee
data:
  config-file: |
    groups:
    - BBSO-01-17
    - BBSO-02-17
    - BBSO-03-17
    services_subnet: 10.10.0.0/24
    clients_subnet: 10.100.0.0/24
    ip_count: 6
    tasks:
      - name: ch1
        description: First challenge for ssh prank
        container: 1
        category: tools
        points: 100

      - name: ch2
        description: Second challenge for dirb
        container: 2
        points: 200
        category: tools
      
      - name: db1
        description: Second challenge for dirb
        container: 2
        points: 200
        category: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: potee
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: explabs/potee-tasks:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: app-env
        volumeMounts:
          - name: app-config
            mountPath: /app/config.yml
            subPath: config-file
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: app-config
          configMap:
            name: app-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: potee
  labels:
    app: app
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: app
    